# Generated by Django 3.0.4 on 2020-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_primarycategory_secondarycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
