# Generated by Django 3.0.4 on 2020-09-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondarycategory',
            name='parent_category',
        ),
    ]
