# Generated by Django 3.0.4 on 2020-10-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201013_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Превью текст'),
        ),
    ]
