# Generated by Django 2.2.7 on 2020-11-22 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201025_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.AlterField(
            model_name='article',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='img/article_avatars', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Article', verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='primarycategory',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='primarycategory',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='тэг'),
        ),
        migrations.AlterField(
            model_name='secondarycategory',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='тэг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='img/avatars', verbose_name='аватар'),
        ),
    ]
